//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 08:41:00 AM PDT 
//


package org.richfaces.bootstrap.demo.jaxb.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 
 *         If the tag library XML file contains individual function
 *         declarations rather than pointing to a library-class or a
 *         declaring a composite-library name, the individual functions are
 *         enclosed in function elements.
 * 
 *       
 * 
 * <p>Java class for facelet-taglib-functionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facelet-taglib-functionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="function-name" type="{http://java.sun.com/xml/ns/javaee}string"/>
 *         &lt;element name="function-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType"/>
 *         &lt;element name="function-signature" type="{http://java.sun.com/xml/ns/javaee}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facelet-taglib-functionType", propOrder = {
    "description",
    "displayName",
    "icon",
    "functionName",
    "functionClass",
    "functionSignature"
})
public class FaceletTaglibFunctionType {

    protected List<DescriptionType> description;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    protected List<IconType> icon;
    @XmlElement(name = "function-name", required = true)
    protected String functionName;
    @XmlElement(name = "function-class", required = true)
    protected FullyQualifiedClassType functionClass;
    @XmlElement(name = "function-signature", required = true)
    protected String functionSignature;

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     *
     *
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the displayName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayNameType }
     *
     *
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the icon property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IconType }
     *
     *
     */
    public List<IconType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<IconType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the functionName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * Sets the value of the functionName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFunctionName(String value) {
        this.functionName = value;
    }

    /**
     * Gets the value of the functionClass property.
     *
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType getFunctionClass() {
        return functionClass;
    }

    /**
     * Sets the value of the functionClass property.
     *
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *
     */
    public void setFunctionClass(FullyQualifiedClassType value) {
        this.functionClass = value;
    }

    /**
     * Gets the value of the functionSignature property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFunctionSignature() {
        return functionSignature;
    }

    /**
     * Sets the value of the functionSignature property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionSignature(String value) {
        this.functionSignature = value;
    }

}
