//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 08:41:00 AM PDT 
//


package org.richfaces.bootstrap.demo.jaxb.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 
 *         Within a tag element, the validator element encapsulates
 *         information specific to a JSF Validator.
 * 
 *       
 * 
 * <p>Java class for facelet-taglib-tag-validatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facelet-taglib-tag-validatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="validator-id" type="{http://java.sun.com/xml/ns/javaee}string"/>
 *         &lt;element name="handler-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType" minOccurs="0"/>
 *         &lt;element name="validator-extension" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-validator-extensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facelet-taglib-tag-validatorType", propOrder = {
    "description",
    "displayName",
    "icon",
    "validatorId",
    "handlerClass",
    "validatorExtension"
})
public class FaceletTaglibTagValidatorType {

    protected List<DescriptionType> description;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    protected List<IconType> icon;
    @XmlElement(name = "validator-id", required = true)
    protected String validatorId;
    @XmlElement(name = "handler-class")
    protected FullyQualifiedClassType handlerClass;
    @XmlElement(name = "validator-extension")
    protected List<FaceletTaglibTagValidatorExtensionType> validatorExtension;

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     *
     *
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the displayName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.DisplayNameType }
     *
     *
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the icon property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IconType }
     *
     *
     */
    public List<IconType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<IconType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the validatorId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValidatorId() {
        return validatorId;
    }

    /**
     * Sets the value of the validatorId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValidatorId(String value) {
        this.validatorId = value;
    }

    /**
     * Gets the value of the handlerClass property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType getHandlerClass() {
        return handlerClass;
    }

    /**
     * Sets the value of the handlerClass property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public void setHandlerClass(FullyQualifiedClassType value) {
        this.handlerClass = value;
    }

    /**
     * Gets the value of the validatorExtension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validatorExtension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidatorExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagValidatorExtensionType }
     * 
     * 
     */
    public List<FaceletTaglibTagValidatorExtensionType> getValidatorExtension() {
        if (validatorExtension == null) {
            validatorExtension = new ArrayList<FaceletTaglibTagValidatorExtensionType>();
        }
        return this.validatorExtension;
    }

}
