//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 08:41:00 AM PDT 
//


package org.richfaces.bootstrap.demo.jaxb.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 
 *         If the tag library XML file contains individual tag
 *         declarations rather than pointing to a library-class or a
 *         declaring a composite-library name, the individual tags are
 *         enclosed in tag elements.
 * 
 *       
 * 
 * <p>Java class for facelet-taglib-tagType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facelet-taglib-tagType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="tag-name" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-canonical-nameType"/>
 *         &lt;choice>
 *           &lt;element name="handler-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType"/>
 *           &lt;element name="behavior" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-behaviorType"/>
 *           &lt;element name="component" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-componentType"/>
 *           &lt;element name="converter" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-converterType"/>
 *           &lt;element name="validator" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-validatorType"/>
 *           &lt;element name="source" type="{http://java.sun.com/xml/ns/javaee}string"/>
 *         &lt;/choice>
 *         &lt;element name="attribute" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-attributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tag-extension" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tag-extensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facelet-taglib-tagType", propOrder = {
    "description",
    "displayName",
    "icon",
    "tagName",
    "handlerClass",
    "behavior",
    "component",
    "converter",
    "validator",
    "source",
    "attribute",
    "tagExtension"
})
public class FaceletTaglibTagType {

    protected List<DescriptionType> description;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    protected List<IconType> icon;
    @XmlElement(name = "tag-name", required = true)
    protected FaceletTaglibCanonicalNameType tagName;
    @XmlElement(name = "handler-class")
    protected FullyQualifiedClassType handlerClass;
    protected FaceletTaglibTagBehaviorType behavior;
    protected FaceletTaglibTagComponentType component;
    protected FaceletTaglibTagConverterType converter;
    protected FaceletTaglibTagValidatorType validator;
    protected String source;
    protected List<FaceletTaglibTagAttributeType> attribute;
    @XmlElement(name = "tag-extension")
    protected List<FaceletTaglibTagExtensionType> tagExtension;

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     *
     *
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the displayName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.DisplayNameType }
     *
     *
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the icon property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.IconType }
     *
     *
     */
    public List<IconType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<IconType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the tagName property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibCanonicalNameType }
     *
     */
    public FaceletTaglibCanonicalNameType getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibCanonicalNameType }
     *
     */
    public void setTagName(FaceletTaglibCanonicalNameType value) {
        this.tagName = value;
    }

    /**
     * Gets the value of the handlerClass property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType getHandlerClass() {
        return handlerClass;
    }

    /**
     * Sets the value of the handlerClass property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public void setHandlerClass(FullyQualifiedClassType value) {
        this.handlerClass = value;
    }

    /**
     * Gets the value of the behavior property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagBehaviorType }
     *
     */
    public FaceletTaglibTagBehaviorType getBehavior() {
        return behavior;
    }

    /**
     * Sets the value of the behavior property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagBehaviorType }
     *
     */
    public void setBehavior(FaceletTaglibTagBehaviorType value) {
        this.behavior = value;
    }

    /**
     * Gets the value of the component property.
     *
     * @return
     *     possible object is
     *     {@link FaceletTaglibTagComponentType }
     *
     */
    public FaceletTaglibTagComponentType getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     *
     * @param value
     *     allowed object is
     *     {@link FaceletTaglibTagComponentType }
     *
     */
    public void setComponent(FaceletTaglibTagComponentType value) {
        this.component = value;
    }

    /**
     * Gets the value of the converter property.
     *
     * @return
     *     possible object is
     *     {@link FaceletTaglibTagConverterType }
     *
     */
    public FaceletTaglibTagConverterType getConverter() {
        return converter;
    }

    /**
     * Sets the value of the converter property.
     *
     * @param value
     *     allowed object is
     *     {@link FaceletTaglibTagConverterType }
     *
     */
    public void setConverter(FaceletTaglibTagConverterType value) {
        this.converter = value;
    }

    /**
     * Gets the value of the validator property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagValidatorType }
     *
     */
    public FaceletTaglibTagValidatorType getValidator() {
        return validator;
    }

    /**
     * Sets the value of the validator property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagValidatorType }
     *
     */
    public void setValidator(FaceletTaglibTagValidatorType value) {
        this.validator = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the attribute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FaceletTaglibTagAttributeType }
     *
     *
     */
    public List<FaceletTaglibTagAttributeType> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<FaceletTaglibTagAttributeType>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the tagExtension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagExtension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagExtensionType }
     * 
     * 
     */
    public List<FaceletTaglibTagExtensionType> getTagExtension() {
        if (tagExtension == null) {
            tagExtension = new ArrayList<FaceletTaglibTagExtensionType>();
        }
        return this.tagExtension;
    }

}
