//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 08:41:00 AM PDT 
//


package org.richfaces.bootstrap.demo.jaxb.javaee;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 
 *         The top level XML element in a facelet tag library XML file.
 * 
 *       
 * 
 * <p>Java class for facelet-taglibType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facelet-taglibType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;choice>
 *           &lt;element name="library-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType"/>
 *           &lt;sequence>
 *             &lt;element name="namespace" type="{http://java.sun.com/xml/ns/javaee}string"/>
 *             &lt;element name="composite-library-name" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType" minOccurs="0"/>
 *             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *               &lt;element name="tag" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-tagType"/>
 *               &lt;element name="function" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-functionType"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="taglib-extension" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-extensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="version" use="required" type="{http://java.sun.com/xml/ns/javaee}facelet-taglib-versionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facelet-taglibType", propOrder = {
    "description",
    "displayName",
    "icon",
    "libraryClass",
    "namespace",
    "compositeLibraryName",
    "tagOrFunction",
    "taglibExtension"
})
public class FaceletTaglibType {

    protected List<DescriptionType> description;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    protected List<IconType> icon;
    @XmlElement(name = "library-class")
    protected FullyQualifiedClassType libraryClass;
    protected String namespace;
    @XmlElement(name = "composite-library-name")
    protected FullyQualifiedClassType compositeLibraryName;
    @XmlElements({
        @XmlElement(name = "function", type = FaceletTaglibFunctionType.class),
        @XmlElement(name = "tag", type = FaceletTaglibTagType.class)
    })
    protected List<Object> tagOrFunction;
    @XmlElement(name = "taglib-extension")
    protected List<FaceletTaglibExtensionType> taglibExtension;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String version;

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     *
     *
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the displayName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayNameType }
     *
     *
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the icon property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IconType }
     *
     *
     */
    public List<IconType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<IconType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the libraryClass property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType getLibraryClass() {
        return libraryClass;
    }

    /**
     * Sets the value of the libraryClass property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public void setLibraryClass(FullyQualifiedClassType value) {
        this.libraryClass = value;
    }

    /**
     * Gets the value of the namespace property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.String }
     *
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.String }
     *
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the compositeLibraryName property.
     *
     * @return
     *     possible object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType getCompositeLibraryName() {
        return compositeLibraryName;
    }

    /**
     * Sets the value of the compositeLibraryName property.
     *
     * @param value
     *     allowed object is
     *     {@link org.richfaces.bootstrap.demo.jaxb.javaee.FullyQualifiedClassType }
     *
     */
    public void setCompositeLibraryName(FullyQualifiedClassType value) {
        this.compositeLibraryName = value;
    }

    /**
     * Gets the value of the tagOrFunction property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagOrFunction property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagOrFunction().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibFunctionType }
     * {@link org.richfaces.bootstrap.demo.jaxb.javaee.FaceletTaglibTagType }
     *
     *
     */
    public List<Object> getTagOrFunction() {
        if (tagOrFunction == null) {
            tagOrFunction = new ArrayList<Object>();
        }
        return this.tagOrFunction;
    }

    /**
     * Gets the value of the taglibExtension property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taglibExtension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaglibExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FaceletTaglibExtensionType }
     *
     *
     */
    public List<FaceletTaglibExtensionType> getTaglibExtension() {
        if (taglibExtension == null) {
            taglibExtension = new ArrayList<FaceletTaglibExtensionType>();
        }
        return this.taglibExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setVersion(java.lang.String value) {
        this.version = value;
    }

}
