//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.30 at 08:41:00 AM PDT 
//


package org.richfaces.bootstrap.demo.jaxb.javaee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.java.xml.ns.javaee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FaceletTaglib_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "facelet-taglib");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.java.xml.ns.javaee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FaceletTaglibTagValidatorExtensionType }
     *
     */
    public FaceletTaglibTagValidatorExtensionType createFaceletTaglibTagValidatorExtensionType() {
        return new FaceletTaglibTagValidatorExtensionType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagAttributeType }
     *
     */
    public FaceletTaglibTagAttributeType createFaceletTaglibTagAttributeType() {
        return new FaceletTaglibTagAttributeType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagBehaviorType }
     *
     */
    public FaceletTaglibTagBehaviorType createFaceletTaglibTagBehaviorType() {
        return new FaceletTaglibTagBehaviorType();
    }

    /**
     * Create an instance of {@link FaceletTaglibFunctionType }
     *
     */
    public FaceletTaglibFunctionType createFaceletTaglibFunctionType() {
        return new FaceletTaglibFunctionType();
    }

    /**
     * Create an instance of {@link XsdStringType }
     *
     */
    public XsdStringType createXsdStringType() {
        return new XsdStringType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagConverterExtensionType }
     *
     */
    public FaceletTaglibTagConverterExtensionType createFaceletTaglibTagConverterExtensionType() {
        return new FaceletTaglibTagConverterExtensionType();
    }

    /**
     * Create an instance of {@link JavaIdentifierType }
     *
     */
    public JavaIdentifierType createJavaIdentifierType() {
        return new JavaIdentifierType();
    }

    /**
     * Create an instance of {@link IconType }
     *
     */
    public IconType createIconType() {
        return new IconType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagValidatorType }
     *
     */
    public FaceletTaglibTagValidatorType createFaceletTaglibTagValidatorType() {
        return new FaceletTaglibTagValidatorType();
    }

    /**
     * Create an instance of {@link FullyQualifiedClassType }
     *
     */
    public FullyQualifiedClassType createFullyQualifiedClassType() {
        return new FullyQualifiedClassType();
    }

    /**
     * Create an instance of {@link FaceletTaglibType }
     *
     */
    public FaceletTaglibType createFaceletTaglibType() {
        return new FaceletTaglibType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagExtensionType }
     *
     */
    public FaceletTaglibTagExtensionType createFaceletTaglibTagExtensionType() {
        return new FaceletTaglibTagExtensionType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagBehaviorExtensionType }
     *
     */
    public FaceletTaglibTagBehaviorExtensionType createFaceletTaglibTagBehaviorExtensionType() {
        return new FaceletTaglibTagBehaviorExtensionType();
    }

    /**
     * Create an instance of {@link FaceletTaglibExtensionType }
     *
     */
    public FaceletTaglibExtensionType createFaceletTaglibExtensionType() {
        return new FaceletTaglibExtensionType();
    }

    /**
     * Create an instance of {@link DisplayNameType }
     *
     */
    public DisplayNameType createDisplayNameType() {
        return new DisplayNameType();
    }

    /**
     * Create an instance of {@link String }
     *
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link FaceletTaglibCanonicalNameType }
     *
     */
    public FaceletTaglibCanonicalNameType createFaceletTaglibCanonicalNameType() {
        return new FaceletTaglibCanonicalNameType();
    }

    /**
     * Create an instance of {@link org.richfaces.bootstrap.demo.jaxb.javaee.PathType }
     *
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     *
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagConverterType }
     *
     */
    public FaceletTaglibTagConverterType createFaceletTaglibTagConverterType() {
        return new FaceletTaglibTagConverterType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagComponentExtensionType }
     *
     */
    public FaceletTaglibTagComponentExtensionType createFaceletTaglibTagComponentExtensionType() {
        return new FaceletTaglibTagComponentExtensionType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagType }
     *
     */
    public FaceletTaglibTagType createFaceletTaglibTagType() {
        return new FaceletTaglibTagType();
    }

    /**
     * Create an instance of {@link FaceletTaglibTagComponentType }
     *
     */
    public FaceletTaglibTagComponentType createFaceletTaglibTagComponentType() {
        return new FaceletTaglibTagComponentType();
    }

    /**
     * Create an instance of {@link GenericBooleanType }
     *
     */
    public GenericBooleanType createGenericBooleanType() {
        return new GenericBooleanType();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link FaceletTaglibType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "facelet-taglib")
    public JAXBElement<FaceletTaglibType> createFaceletTaglib(FaceletTaglibType value) {
        return new JAXBElement<FaceletTaglibType>(_FaceletTaglib_QNAME, FaceletTaglibType.class, null, value);
    }

}
