//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.16 at 01:15:02 AM EET 
//


package org.richfaces.taglib.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.richfaces.taglib.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Taglib_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "taglib");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.richfaces.taglib.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TldAttributeType }
     * 
     */
    public TldAttributeType createTldAttributeType() {
        return new TldAttributeType();
    }

    /**
     * Create an instance of {@link TldExtensionType }
     * 
     */
    public TldExtensionType createTldExtensionType() {
        return new TldExtensionType();
    }

    /**
     * Create an instance of {@link TldDeferredValueType }
     * 
     */
    public TldDeferredValueType createTldDeferredValueType() {
        return new TldDeferredValueType();
    }

    /**
     * Create an instance of {@link IconType }
     * 
     */
    public IconType createIconType() {
        return new IconType();
    }

    /**
     * Create an instance of {@link TldTaglibType }
     * 
     */
    public TldTaglibType createTldTaglibType() {
        return new TldTaglibType();
    }

    /**
     * Create an instance of {@link FunctionType }
     * 
     */
    public FunctionType createFunctionType() {
        return new FunctionType();
    }

    /**
     * Create an instance of {@link TldDeferredMethodType }
     * 
     */
    public TldDeferredMethodType createTldDeferredMethodType() {
        return new TldDeferredMethodType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TldTaglibType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "taglib")
    public JAXBElement<TldTaglibType> createTaglib(TldTaglibType value) {
        return new JAXBElement<TldTaglibType>(_Taglib_QNAME, TldTaglibType.class, null, value);
    }

}
