//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.16 at 01:15:02 AM EET 
//


package org.richfaces.taglib.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 				The attribute element defines an attribute for the
 * 				nesting
 * 				tag. The attribute element may have several subelements
 * 				defining:
 * 
 * 				description a description of the attribute
 * 
 * 				name the name of
 * 				the attribute
 * 
 * 				required whether the attribute is required or
 * 				optional
 * 
 * 				rtexprvalue whether the attribute is a runtime attribute
 * 
 * 				type the
 * 				type of the attributes
 * 
 * 				fragment whether this attribute is a fragment
 * 
 * 				deferred-value present if this attribute is to be parsed as a
 * 				javax.el.ValueExpression
 * 
 * 				deferred-method present if this attribute is
 * 				to be parsed as a
 * 				javax.el.MethodExpression
 * 
 *       
 * 
 * <p>Java class for tld-attributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tld-attributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;sequence minOccurs="0">
 *               &lt;element name="rtexprvalue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *               &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *             &lt;/sequence>
 *             &lt;choice>
 *               &lt;element name="deferred-value" type="{http://java.sun.com/xml/ns/javaee}tld-deferred-valueType" minOccurs="0"/>
 *               &lt;element name="deferred-method" type="{http://java.sun.com/xml/ns/javaee}tld-deferred-methodType" minOccurs="0"/>
 *             &lt;/choice>
 *           &lt;/sequence>
 *           &lt;element name="fragment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tld-attributeType", propOrder = {
    "description",
    "name",
    "required",
    "rtexprvalue",
    "type",
    "deferredValue",
    "deferredMethod",
    "fragment"
})
public class TldAttributeType {

    @XmlElementWrapper(name = "description")
    @XmlAnyElement(lax = true)
    @XmlMixed
    protected List<Object> description;
    @XmlElement(required = true)
    protected String name;
    protected Boolean required;
    protected Boolean rtexprvalue = true;
    protected String type;
    @XmlElement(name = "deferred-value")
    protected TldDeferredValueType deferredValue;
    @XmlElement(name = "deferred-method")
    protected TldDeferredMethodType deferredMethod;
    protected Boolean fragment;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<Object> getDescription() {
        if (description == null) {
            description = new ArrayList<Object>();
        }
        return this.description;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the rtexprvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRtexprvalue() {
        return rtexprvalue;
    }

    /**
     * Sets the value of the rtexprvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRtexprvalue(Boolean value) {
        this.rtexprvalue = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the deferredValue property.
     * 
     * @return
     *     possible object is
     *     {@link TldDeferredValueType }
     *     
     */
    public TldDeferredValueType getDeferredValue() {
        return deferredValue;
    }

    /**
     * Sets the value of the deferredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TldDeferredValueType }
     *     
     */
    public void setDeferredValue(TldDeferredValueType value) {
        this.deferredValue = value;
    }

    /**
     * Gets the value of the deferredMethod property.
     * 
     * @return
     *     possible object is
     *     {@link TldDeferredMethodType }
     *     
     */
    public TldDeferredMethodType getDeferredMethod() {
        return deferredMethod;
    }

    /**
     * Sets the value of the deferredMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TldDeferredMethodType }
     *     
     */
    public void setDeferredMethod(TldDeferredMethodType value) {
        this.deferredMethod = value;
    }

    /**
     * Gets the value of the fragment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFragment() {
        return fragment;
    }

    /**
     * Sets the value of the fragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFragment(Boolean value) {
        this.fragment = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
